# up with system, be careful about routing table
enabled:
#  - aaa
#  - bbb

# resolve hostname every interval
ddns:
  # check every interval
  interval: 60
  # when last handshake time is max-last-handshake before now, update interface
  max_last_handshake: 150
  iface:
#    - ccc
#    - ddd
