#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

WG_QUICK_OP_CONF="/etc/wg-quick-op.toml"

start_service() {
    procd_open_instance
    procd_set_param command wg-quick-op service -c $WG_QUICK_OP_CONF
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}
