name: Build and Release
on:
  release:
    types: [created]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://go.dev/dl/go1.20.4.linux-amd64.tar.gz"
        binary_name: "wg-quick-op"
        extra_files: LICENSE README.md
